package com.skyheights.realestate.modules.financial.dto;

import com.skyheights.realestate.modules.financial.enums.InvoiceStatus;
import com.skyheights.realestate.modules.financial.enums.InvoiceType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InvoiceResponse {

    private Long id;
    private String uuid;
    private Long orgId;
    private Long propertyId;
    private String propertyName;
    private Long unitId;
    private String unitNumber;
    private Long tenantId;
    private String tenantName;
    private Long leaseId;
    private String invoiceNumber;
    private InvoiceType type;
    private LocalDate billingPeriodStart;
    private LocalDate billingPeriodEnd;
    private LocalDate issueDate;
    private LocalDate dueDate;
    private BigDecimal subtotal;
    private BigDecimal taxAmount;
    private BigDecimal lateFeeAmount;
    private BigDecimal discountAmount;
    private BigDecimal totalAmount;
    private BigDecimal amountPaid;
    private BigDecimal balanceDue;
    private InvoiceStatus status;
    private String notes;
    private String pdfS3Key;
    private String pdfPresignedUrl;
    private Boolean autoGenerated;
    private List<LineItemResponse> lineItems;

    private Instant createdAt;
    private Instant updatedAt;

    // Computed
    private long daysOverdue;
    private boolean overdue;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class LineItemResponse {
        private Long id;
        private String description;
        private BigDecimal quantity;
        private BigDecimal unitPrice;
        private BigDecimal amount;
        private String type;
    }
}
